### ISSUE TITLE
Needs aeson >= 0.11 in cabal file

### ISSUE THREAD

**Issue by mircead3** [seagreen/hjsonschema#41]
It needs .:! which was introduced in 0.11.0.0.

**Comment by seagreen** [comment]
Thanks! Included it in Hackage release `1.1.0.0`.

**Comment by mircead3** [comment]
Hi Ian,

Using your example (module Simple), I get the "We validated bad data.” error for some very simple schema such as {"type": "string”} and data = “abc”.
What am I missing?

Also, could you explain this line, i.e., why is this a success?

```
     [D4.Failure (D4.Ref D4.UniqueItems) _ _ _] -> return () -- Success.
```

Thank you for your help,

Mircea

**Comment by seagreen** [comment]
Hey,

In that example the hardcoded data being tested -- `badData = toJSON (["foo", "foo"] :: [String])` -- is invalid.

So the example is working correctly (and returns `return ()` instead of throwing an error) when it sees the failure it expects. This failure is `D4.Ref D4.UniqueItems` (there's a `$ref` pointing to a schema the requires `uniqueItems`, but the data we're validating contains an array which has duplicates instead of everything in it being unique.

Since you're not trying to show how the library works but rather actually validate some data, you want to do something else with the result of `D4.fetchFilesystemAndValidate schemaWithURI yourData`. Knowing that `Right ()` means the data is valid for this schema, and `Left anything` means something is wrong, you can proceed from there.

Let me know if anything else is unclear. I've got the library working correctly, but I'd still like to have a cleaner API and better examples, so knowing where people are hitting issues is real help.

**Comment by mircead3** [comment]
Thanks, now I get it.
I thought the code is an example on how to do validation and I got confused by the error messages.

Mircea

**Comment by mircead3** [comment]
Thanks, now I get it.
I thought the code is an example on how to do validation and I got confused
by the error messages.

Mircea

On Aug 17, 2016, at 7:15 PM, Ian Jeffries notifications@github.com wrote:

Hey,

In that example the hardcoded data being tested -- badData = toJSON
(["foo", "foo"] :: [String]) -- is invalid.

So the example is working correctly (and returns return () instead of
throwing an error) when it sees the failure it expects. This failure is D4.Ref
D4.UniqueItems (there's a $ref pointing to a schema the requires uniqueItems,
but the data we're validating contains an array which has duplicates
instead of everything in it being unique.

Since you're not trying to show how the library works but rather actually
validate some data, you want to do something else with the result of
D4.fetchFilesystemAndValidate
schemaWithURI yourData. Knowing that Right () means the data is valid for
this schema, and Left anything means something is wrong, you can proceed
from there.

Let me know if anything else is unclear. I've got the library working
correctly, but I'd still like to have a cleaner API and better examples, so
knowing where people are hitting issues is real help.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/seagreen/hjsonschema/issues/41#issuecomment-240605047,
or mute the thread
